export const sharesPhoto = [
  {
    id: '1',
    photos: [
      'https://i.ibb.co/pB2tYhzr/phone.jpg',
      'https://i.ibb.co/gbLkjzrk/phone1.jpg',
      'https://i.ibb.co/s9kNq82S/img.jpg',
    ],
    discount: 4,
    text: 'Смартфон Apple iPhone 13 128GB',
    price: 75999,
    valute: '₴',
    available: false,
  },
  {
    id: '2',
    photos: [
      'https://i.ibb.co/pB2tYhzr/phone.jpg',
      'https://i.ibb.co/gbLkjzrk/phone1.jpg',
      'https://i.ibb.co/s9kNq82S/img.jpg',
    ],
    discount: 10,
    text: 'Смартфон Apple iPhone 12 64GB',
    price: 45999,
    valute: '₴',
    available: true,
  },
  {
    id: '3',
    photos: [
      'https://i.ibb.co/pB2tYhzr/phone.jpg',
      'https://i.ibb.co/gbLkjzrk/phone1.jpg',
      'https://i.ibb.co/s9kNq82S/img.jpg',
    ],
    discount: 12,
    text: 'Смартфон HONOR X8A 6/128GB',
    price: 13600,
    valute: '₴',
    available: true,
  },
  {
    id: '4',
    photos: [
      'https://i.ibb.co/pB2tYhzr/phone.jpg',
      'https://i.ibb.co/gbLkjzrk/phone1.jpg',
      'https://i.ibb.co/s9kNq82S/img.jpg',
    ],
    discount: 12,
    text: 'Смартфон HONOR X8A 6/128GB',
    price: 13600,
    valute: '₴',
    available: true,
  },
  {
    id: '5',
    photos: [
      'https://i.ibb.co/pB2tYhzr/phone.jpg',
      'https://i.ibb.co/gbLkjzrk/phone1.jpg',
      'https://i.ibb.co/s9kNq82S/img.jpg',
    ],
    discount: 12,
    text: 'Смартфон HONOR X8A 6/128GB',
    price: 13600,
    valute: '₴',
    available: true,
  },
  {
    id: '6',
    photos: [
      'https://i.ibb.co/pB2tYhzr/phone.jpg',
      'https://i.ibb.co/gbLkjzrk/phone1.jpg',
      'https://i.ibb.co/s9kNq82S/img.jpg',
    ],
    discount: 12,
    text: 'Смартфон HONOR X8A 6/128GB',
    price: 13600,
    valute: '₴',
    available: true,
  },
  {
    id: '7',
    photos: [
      'https://i.ibb.co/pB2tYhzr/phone.jpg',
      'https://i.ibb.co/gbLkjzrk/phone1.jpg',
      'https://i.ibb.co/s9kNq82S/img.jpg',
    ],
    discount: 12,
    text: 'Смартфон HONOR X8A 6/128GB',
    price: 13600,
    valute: '₴',
    available: true,
  },
  {
    id: '8',
    photos: [
      'https://i.ibb.co/pB2tYhzr/phone.jpg',
      'https://i.ibb.co/gbLkjzrk/phone1.jpg',
      'https://i.ibb.co/s9kNq82S/img.jpg',
    ],
    discount: 12,
    text: 'Смартфон HONOR X8A 6/128GB',
    price: 13600,
    valute: '₴',
    available: true,
  },
  {
    id: '9',
    photos: [
      'https://i.ibb.co/pB2tYhzr/phone.jpg',
      'https://i.ibb.co/gbLkjzrk/phone1.jpg',
      'https://i.ibb.co/s9kNq82S/img.jpg',
    ],
    discount: 12,
    text: 'Смартфон HONOR X8A 6/128GB',
    price: 13600,
    valute: '₴',
    available: true,
  },
  {
    id: '10',
    photos: [
      'https://i.ibb.co/pB2tYhzr/phone.jpg',
      'https://i.ibb.co/gbLkjzrk/phone1.jpg',
      'https://i.ibb.co/s9kNq82S/img.jpg',
    ],
    discount: 12,
    text: 'Смартфон HONOR X8A 6/128GB',
    price: 13600,
    valute: '₴',
    available: true,
  },
];
